export const TOGGLE_USER_HAS_VISITED = 'TOGGLE_USER_HAS_VISITED';
export const SHOW_USER_WARNING = 'SHOW_USER_WARNING';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_MODAL = 'SET_MODAL';
